# Generated by Django 2.2.8 on 2021-05-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
