# Generated by Django 2.2.8 on 2021-06-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0003_auto_20210615_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
