# Generated by Django 2.2.8 on 2021-06-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0006_auto_20210626_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_sold',
            field=models.IntegerField(default=0),
        ),
    ]
