# Generated by Django 2.2.8 on 2021-05-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0007_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
