# Generated by Django 2.2.8 on 2021-05-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_backend', '0008_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
