# Generated by Django 2.2.8 on 2021-06-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='one_click_purchasing',
            field=models.BooleanField(default=False),
        ),
    ]
